// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMqSxFFtHXS85Nr7HSB9vkdc2hWF4SF7Y',
    appId: '1:134855099076:android:05753575f03ae58f9dff91',
    messagingSenderId: '134855099076',
    projectId: 'newbeginnings-7fed9',
    databaseURL: 'https://newbeginnings-7fed9-default-rtdb.firebaseio.com',
    storageBucket: 'newbeginnings-7fed9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGwnIOYhn7zZkNsk8GH7Jkz_mJt9EyIs4',
    appId: '1:134855099076:ios:35ad79ecae6f780e9dff91',
    messagingSenderId: '134855099076',
    projectId: 'newbeginnings-7fed9',
    databaseURL: 'https://newbeginnings-7fed9-default-rtdb.firebaseio.com',
    storageBucket: 'newbeginnings-7fed9.appspot.com',
    iosClientId: '134855099076-sp0b06jcje66dn9l76gdjdvqabgcqeem.apps.googleusercontent.com',
    iosBundleId: 'com.newbeginnings.mobile.app',
  );
}
